# Generated by Django 5.1.4 on 2024-12-25 19:29

import django.utils.timezone
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_premiumcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiplayground',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-date_earned']},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='devopsshowcase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='guestpostrequest',
            options={'ordering': ['-submitted']},
        ),
        migrations.AlterModelOptions(
            name='interactiveroadmap',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at']},
        ),
        migrations.AlterModelOptions(
            name='premiumcontent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projecthighlight',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='devopsshowcase',
            name='infrastructure_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='devops_showcases/diagrams/'),
        ),
        migrations.AddField(
            model_name='devopsshowcase',
            name='pipeline_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
