# Generated by Django 5.1.4 on 2024-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_interactiveroadmap_roadmap_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='github_repo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/images/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/videos/'),
        ),
    ]
