# Generated by Django 5.1.4 on 2024-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('education', 'Education'), ('internship', 'Internship'), ('certification', 'Certification'), ('work', 'Work Experience')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_range', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'type', '-date_range'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('github', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('stack', models.CharField(max_length=500)),
                ('github_url', models.URLField()),
                ('live_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='project_videos/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('SiAmazonaws', 'AWS'), ('SiDocker', 'Docker'), ('SiKubernetes', 'Kubernetes'), ('SiTerraform', 'Terraform'), ('SiJenkins', 'Jenkins'), ('SiDjango', 'Django'), ('FaNodeJs', 'Node.js'), ('SiPostman', 'Postman (REST API)'), ('SiFastapi', 'FastAPI'), ('FaReact', 'React'), ('SiNextdotjs', 'Next.js'), ('SiTypescript', 'TypeScript'), ('SiTailwindcss', 'TailwindCSS'), ('SiUnocss', 'UnoCSS'), ('FaSass', 'Sass'), ('SiFramer', 'Framer Motion'), ('SiFirebase', 'Firebase'), ('SiHugo', 'Hugo'), ('SiRedux', 'Redux'), ('FaHtml5', 'HTML5'), ('FaPython', 'Python'), ('SiJavascript', 'JavaScript'), ('SiLatex', 'LaTeX'), ('SiMatlabSimulink', 'MATLAB'), ('FaGithub', 'GitHub'), ('FaGitAlt', 'Git'), ('SiVisualstudiocode', 'VS Code'), ('FaFigma', 'Figma'), ('SiCanva', 'Canva'), ('SiNpm', 'NPM'), ('SiYarn', 'Yarn'), ('SiJest', 'Jest'), ('FaCss3Alt', 'CSS3'), ('FaBootstrap', 'Bootstrap'), ('FaCode', 'Default (Code Icon)')], default='FaCode', max_length=50)),
                ('category', models.CharField(choices=[('devops', 'DevOps'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('programming', 'Programming'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Phone', 'Phone'), ('Location', 'Location')], max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
    ]
