# Generated by Django 5.1.4 on 2024-12-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(choices=[('SiAmazonaws', 'AWS'), ('SiDocker', 'Docker'), ('SiKubernetes', 'Kubernetes'), ('SiTerraform', 'Terraform'), ('SiJenkins', 'Jenkins'), ('SiDjango', 'Django'), ('FaNodeJs', 'Node.js'), ('SiPostman', 'Postman (REST API)'), ('SiFastapi', 'FastAPI'), ('FaReact', 'React'), ('SiNextdotjs', 'Next.js'), ('SiTypescript', 'TypeScript'), ('SiTailwindcss', 'TailwindCSS'), ('SiUnocss', 'UnoCSS'), ('FaSass', 'Sass'), ('SiFramer', 'Framer Motion'), ('SiFirebase', 'Firebase'), ('SiHugo', 'Hugo'), ('SiRedux', 'Redux'), ('FaHtml5', 'HTML5'), ('FaPython', 'Python'), ('SiJavascript', 'JavaScript'), ('SiLatex', 'LaTeX'), ('SiMatlabSimulink', 'MATLAB'), ('FaGithub', 'GitHub'), ('FaGitAlt', 'Git'), ('SiVisualstudiocode', 'VS Code'), ('FaFigma', 'Figma'), ('SiCanva', 'Canva'), ('SiNpm', 'NPM'), ('SiYarn', 'Yarn'), ('SiJest', 'Jest'), ('FaCss3Alt', 'CSS3'), ('FaBootstrap', 'Bootstrap'), ('FaLaptopCode', 'Software Engineering'), ('FaFlask', 'Chemical Engineering'), ('FaPaintBrush', 'UX/UI Designing'), ('FaChartLine', 'Financial Analysis'), ('FaGlobe', 'Web Development'), ('FaCode', 'Default (Code Icon)')], default='FaCode', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatido',
            name='icon',
            field=models.CharField(choices=[('SiAmazonaws', 'AWS'), ('SiDocker', 'Docker'), ('SiKubernetes', 'Kubernetes'), ('SiTerraform', 'Terraform'), ('SiJenkins', 'Jenkins'), ('SiDjango', 'Django'), ('FaNodeJs', 'Node.js'), ('SiPostman', 'Postman (REST API)'), ('SiFastapi', 'FastAPI'), ('FaReact', 'React'), ('SiNextdotjs', 'Next.js'), ('SiTypescript', 'TypeScript'), ('SiTailwindcss', 'TailwindCSS'), ('SiUnocss', 'UnoCSS'), ('FaSass', 'Sass'), ('SiFramer', 'Framer Motion'), ('SiFirebase', 'Firebase'), ('SiHugo', 'Hugo'), ('SiRedux', 'Redux'), ('FaHtml5', 'HTML5'), ('FaPython', 'Python'), ('SiJavascript', 'JavaScript'), ('SiLatex', 'LaTeX'), ('SiMatlabSimulink', 'MATLAB'), ('FaGithub', 'GitHub'), ('FaGitAlt', 'Git'), ('SiVisualstudiocode', 'VS Code'), ('FaFigma', 'Figma'), ('SiCanva', 'Canva'), ('SiNpm', 'NPM'), ('SiYarn', 'Yarn'), ('SiJest', 'Jest'), ('FaCss3Alt', 'CSS3'), ('FaBootstrap', 'Bootstrap'), ('FaLaptopCode', 'Software Engineering'), ('FaFlask', 'Chemical Engineering'), ('FaPaintBrush', 'UX/UI Designing'), ('FaChartLine', 'Financial Analysis'), ('FaGlobe', 'Web Development'), ('FaCode', 'Default (Code Icon)')], default='FaCode', max_length=50),
        ),
    ]
